name: Maven Publish
on:
  release:
    types: [ created ]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: Update Release Version
        run: mvn versions:set -DgenerateBackupPoms=false -DnewVersion=${{ github.event.release.tag_name }}

      - name: Commit Release Version
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Release ${{ github.event.release.tag_name }}"
          git push origin HEAD:master

      - name: Build with Maven
        run: mvn -B -ntp install

      - name: Publish to GitHub Packages
        run: mvn -B -ntp -DskipTests deploy
